name: af2seq-arm64
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - absl-py>=1.0
  - biopython>=1.79
  - dm-tree>=0.1.8
  - immutabledict>=3.0
  - numpy>=1.24
  - pandas>=2.0
  - scipy>=1.10
  - ca-certificates
  - certifi
  - openssl
  - tqdm
  - matplotlib
  - seaborn
  - py3dmol
  - pdbfixer
  - openmm>=8.0
  - pip:
    - jax[cpu]
    - dm-haiku>=0.0.12
    - optax>=0.2.0
    - chex>=0.1.8
    - tensorflow>=2.15
    - contextlib2>=21.6.0
    - iminuit>=2.0
    - ml-collections>=0.1.0
    - pyyaml>=6.0
    - tmscoring>=0.4
    - pydssp
